server:
  port: ${server.port}
  address: 0.0.0.0
  servlet:
    context-path: ${server.context-path}

spring:
  application:
    name: aportacion-service

  profiles:
    active: local

  config:
    import: optional:configserver:http://localhost:9999

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  cloud:
    inetutils:
      ignored-interfaces:
        - lo
        - docker0
        - docker.*
        - vboxnet0
        - VirtualBox.*
        - VMware.*
        - 127.0.0.1
      #preferred-networks: ${inetutils.preferred-networks}


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${eureka.instance-ip}
    hostname: ${eureka.instance-host}
    non-secure-port: ${server.port}
    secure-port-enabled: false
    instance-id: "${spring.application.name}:${server.port}:${random.value}"
    metadata-map:
      contextPath: ${server.context-path}
  client:
    service-url:
      defaultZone: ${eureka.registry-server}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
